name: Blog Preview
context: 
  image: '/media/images/blog/welt-der-farben.jpeg'
  category: Know-How
  title: Welt der Farben.
  description: In diesem Blogbeitrag erkunden wir die Welt der Farben, weit Ã¼ber den Horizont von Schwarz und Weiss hinaus.